{% set name = "django-axes" %}
{% set version = "5.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c26167f7ca2003df8358eb23537dffb1d97bd9f44ccef70d5c64a7aba2349456

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - setuptools
    - python
    - django >=2.0
    - django-appconf >=1.0.3
    - django-ipware >=3,<4

test:
  imports:
    - axes

about:
  home: https://pypi.org/project/django-axes/
  summary: django-axes, User lockout in django apps.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
